// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-cgJpgwR57nJK0m_x4LL0WOJxZwSuEXU',
    appId: '1:1026025051687:web:9b88e85aea8d96d00a6002',
    messagingSenderId: '1026025051687',
    projectId: 'inboxie-010',
    authDomain: 'inboxie-010.firebaseapp.com',
    storageBucket: 'inboxie-010.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZqRyaETuBQfSaD6vccUay_fCdaY1ROZA',
    appId: '1:1026025051687:android:02a2fdc26ef3c83d0a6002',
    messagingSenderId: '1026025051687',
    projectId: 'inboxie-010',
    storageBucket: 'inboxie-010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZN1KoBUbK8y8ltb9C4KnWIAZPiSPdzAs',
    appId: '1:1026025051687:ios:11b5612018142e140a6002',
    messagingSenderId: '1026025051687',
    projectId: 'inboxie-010',
    storageBucket: 'inboxie-010.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZN1KoBUbK8y8ltb9C4KnWIAZPiSPdzAs',
    appId: '1:1026025051687:ios:11b5612018142e140a6002',
    messagingSenderId: '1026025051687',
    projectId: 'inboxie-010',
    storageBucket: 'inboxie-010.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-cgJpgwR57nJK0m_x4LL0WOJxZwSuEXU',
    appId: '1:1026025051687:web:a9df0f11799b16b80a6002',
    messagingSenderId: '1026025051687',
    projectId: 'inboxie-010',
    authDomain: 'inboxie-010.firebaseapp.com',
    storageBucket: 'inboxie-010.firebasestorage.app',
  );
}
